drop table if exists post_likes;
drop table if exists comments;
drop table if exists posts;

create table posts(
    id bigint generated by default as identity primary key,
    title varchar(256) not null,
    text varchar(5000) not null,
    likes_count integer not null default 0,
    comments_count integer not null default 0,
    tags varchar(1000) not null default '',
    image blob
);

create table comments(
    id bigint generated by default as identity primary key,
    post_id bigint not null,
    text varchar(1000) not null,
    constraint fk_comments_post_id
        foreign key (post_id) references posts(id)
        on delete cascade
);

create table post_likes(
    post_id bigint not null,
    user_key varchar(255) not null,
    constraint pk_post_likes primary key (post_id, user_key),
    constraint fk_post_likes_post_id
        foreign key (post_id) references posts(id)
        on delete cascade
);

insert into posts(title, text, likes_count, comments_count, tags) values
    ('Первый пост', 'Текст 1', 12, 3, 'java spring'),
    ('Второй пост', 'Текст 2', 5, 1, 'spring backend'),
    ('Третий пост', 'Текст 3', 0, 0, 'testing junit'),
    ('Четвёртый пост', 'Текст 4', 0, 0, 'frontend react'),
    ('Пятый пост', '', 0, 0, 'java markdown');

insert into comments(post_id, text) values
    (1, 'Первый комментарий к первому посту'),
    (1, 'Второй комментарий к первому посту'),
    (1, 'Третий комментарий к первому посту'),
    (2, 'Первый комментарий ко второму посту');
