drop table if exists posts;

create table posts(
id bigint generated by default as identity primary key,
title varchar(256) not null,
text varchar(5000) not null,
likes_count integer not null default 0,
comments_count integer not null default 0
);

insert into posts(title, text, likes_count, comments_count) values
('Первый пост', 'Текст 1', 12, 3),
('Второй пост', 'Текст 2', 5, 1),
('Третий пост', 'Текст 3', 0, 0),
('Четвёртый пост', 'Текст 4', 0, 0),
('Пятый пост', '', 0, 0);